/* tslint:disable */
/* eslint-disable */
/**
 * Monkeytype API
 * Documentation for the endpoints provided by the Monkeytype API server.  Note that authentication is performed with the Authorization HTTP header in the format `Authorization: ApeKey YOUR_APE_KEY`  There is a rate limit of `30 requests per minute` across all endpoints with some endpoints being more strict. Rate limit rates are shared across all ape keys.
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: support@monkeytype.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

